[project]
authors = ["Elena Pianfetti <elena.pianfetti@embl.de>", "Wouter-Michiel Vierdag <michiel.vierdag@embl.de>"]
channels = ["conda-forge", "pytorch"]
description = "Using SubCell for classification in spectrally unmixed images."
name = "Highly multiplexed SubCell"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
loguru = ">=0.7.3,<0.8"
typer = ">=0.21.1,<0.22"
tqdm = ">=4.67.2,<5"

[tool.pixi.pypi-dependencies]
pixi_py = { path = ".", editable = true }

[feature.preprocess.dependencies]
micro_sam = "*"

[feature.subcell.dependencies]
micro_sam = "*"

[feature.preprocess.target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }

[feature.preprocess.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu118" }

[feature.preprocess.tasks]
split-images = "python ./scripts/split_lif.py"
preprocess = "python ./scripts/preprocessing.py"

[environments]
preprocess = { features = ["preprocess"], solve-group = "default" }
subcell = { features = ["subcell"], solve-group = "default" }

[pypi-dependencies]
bioio = "*"
bioio-lif = "*"
bioio-ome-tiff = "*"
bioio-tifffile = ">=1.3.0, <2"
