# plot_config.yaml

marker_size: 6
linewidth: 1.5

condition_colormap:
  Untreated: "#d81b60"
  ActD: "#ffc107"
  SA: "#1e88e5"

plot_linestyles:
  Untreated: solid
  ActD: dashed
  SA: dotted

plot_markers:
  Untreated: o
  ActD: x
  SA: d

plot_facecolors:
  "Untreated": null
  "ActD": null
  "SA": null
  ###########################
  "GroundTruth": null
  "UMX": null
  "UMX_Branched": null

plot_edge_colors:
  "Untreated": 'black'
  "ActD": 'black'
  "SA": null
  ###########################
  "Ground_Truth": 'black'
  "UMX": 'black'
  "UMX_Branched": 'black'