fields:
  - column: condition
    label: Condition
  - column: protein
    label: Protein
  - column: top_class_name
    label: Classification
  - column: unique_cell_id
    label: Unique ID
  #- column: cell_cycle_phase
  #  label: Cell Cycle Phase
show_thumbnail: False
thumbnail_size: 64