# ======================
# Layout
# ======================
min_width: 200
init_alpha: 0.7

max_legend_entries: 31  # maximum number of entries to show in legend (if all subcell classes are present)

# ======================
# Highlighting
# ======================
highlighted_cells: ['FOV3_6', 'FOV3_8']
highlight_color: black
highlight_width: 3

# ======================
# Marker symbols
# ======================
# circle, diamond, square

marker_sizes:
  circle: 8
  diamond: 12
  square: 12

  
# ======================
# Shape configuration
# ======================
shape_by: protein   # cell_cycle_phase | protein | condition

marker_types:
  cell_cycle_phase:
    Interphase: circle
    Prophase: square
    Prometaphase: square
    Metaphase: square
    Anaphase: square
    Telophase: square
    Cytokinesis: square
    Unknown: diamond
    Dying: diamond
    Artifact: diamond
    Problem: diamond
    Unexpected: diamond
    Border: diamond
    Exclude: diamond

  protein:
    alpha-tubulin: diamond
    G3BP1: diamond
    NPM1: square

  condition:
    Untreated: circle
    ActD: circle
    SA: circle

# ====== tooltips ======
tooltip:
  fields:
    - column: condition
      label: Condition
    - column: protein
      label: Protein
    - column: top_class_name
      label: Classification
    - column: unique_cell_id
      label: Unique ID
    #- column: cell_cycle_phase
    #  label: Cell Cycle Phase
  show_thumbnail: False
  thumbnail_size: 64